[package]
name = "kiwi-talk-{{project-name}}"
description = "{{description}}"

version.workspace = true
license.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
