[package]
name = "kiwi-talk-resource"
description = "ipc resource plugin"
publish = false

version.workspace = true
license.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
tauri = { workspace = true }
serde = { workspace = true }

dashmap = "5.5.3"
