changelog:
  categories:
    - title: New Features
      labels:
        - 'Type: Enhancement'
    - title: Bug Fixes
      labels:
        - 'Type: Bug'
    - title: Other Changes
      labels:
        - "*"
      exclude:
        labels:
          - 'Type: Dependency'
    - title: Dependency Updates
      labels:
        - 'Type: Dependency'
