[workspace]
resolver = "2"

members = [
    "./crates/*"
]

[workspace.package]
version = "0.1.0"
license = "Apache-2.0"
authors = ["KiwiTalk contributors"]
edition = "2021"
repository = "https://github.com/KiwiTalk/KiwiTalk"

[workspace.dependencies]
kiwi-talk-client = { path = "./crates/kiwi-talk-client" }
talk-api-client = { path = "./crates/talk-api-client" }
talk-loco-client = { path = "./crates/talk-loco-client" }

