[package]
name = "kiwi-talk-client"
version = "0.1.0"
authors = ["KiwiTalk contributors"]
license = "Apache-2.0"
repository = "https://github.com/KiwiTalk/kiwitalk"
edition = "2021"

[dependencies]
kiwi-talk-db = { path = "../kiwi-talk-db" }
tokio = { version = "1", features = ["full"] }