[package]
name = "kiwi-talk-db"
version = "0.1.0"
authors = ["KiwiTalk contributors"]
license = "Apache-2.0"
repository = "https://github.com/KiwiTalk/kiwitalk"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["rt", "fs", "sync"] }
rusqlite = "0.28.0"
