[package]
name = "kiwi-talk-app"
version = "0.1.0"
description = "A Tauri App"
authors = ["KiwiTalk contributors"]
license = "Apache-2.0"
repository = "https://github.com/KiwiTalk/kiwitalk"
edition = "2021"
rust-version = "1.57"
default-run = "kiwi-talk-app"

[build-dependencies]
tauri-build = { version = "1.0.4", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.0.5", features = ["api-all"] }
tokio = { version = "1", features = ["full"] }
kiwi-talk-client = { path = "../kiwi-talk-client" }
talk-api-client = { path = "../talk-api-client" }

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]
