[package]
name = "kiwi-talk-app"
description = "A Tauri App"
default-run = "kiwi-talk-app"
publish = false

version.workspace = true
license.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true

[build-dependencies]
tauri-build = { version = "1.5.0", features = [] }

[dependencies]
talk-api-internal = { workspace = true }
kiwi-talk-client = { workspace = true }
talk-loco-client = { workspace = true }

kiwi-talk-system = { path = "../system" }
kiwi-talk-result = { path = "../result" }
kiwi-talk-auth = { path = "../auth" }

tokio = { workspace = true, features = ["full"] }
tauri = { workspace = true, features = [ "updater", "api-all", "system-tray"] }
anyhow = { workspace = true, features = ["backtrace"] }
log = { workspace = true }
serde = { workspace = true }

serde_json = "1.0"
tokio-util = { version = "0.7.9", features = ["compat"] }
thiserror = "1.0"
once_cell = "1.18.0"
env_logger = "0.10.0"
parking_lot = "0.12.1"
futures = "0.3.28"
window-shadows = "0.2.1"
num-bigint-dig = "0.8.4"
tauri-plugin-window-state = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v1" }
bincode = "1.3.3"
enum-kinds = "0.5.1"
sha2 = "0.10.8"
serde-byte-array = "0.1.2"
hex = "0.4.3"
arrayvec = { version = "0.7.4", features = ["serde"] }

[features]
default = []
custom-protocol = ["tauri/custom-protocol"]
