[package]
name = "kiwi-talk-system"
description = "Query device's system information"
publish = false

version.workspace = true
license.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
tokio = { workspace = true, features = ["full"] }
tauri = { workspace = true, features = [ "updater", "api-all", "system-tray"] }
anyhow = { workspace = true, features = ["backtrace"] }
log = { workspace = true }

rand = "0.8.5"
base64 = "0.21.4"
hostname = "0.3.1"
sys-locale = "0.3.1"
