on: pull_request

name: Clippy check
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
            components: clippy
      - name: Update apt repository
        run: sudo apt update -y
      - name: Install libraries
        run: sudo apt install -y libdbus-1-dev libgtk-3-dev libsoup2.4-dev libjavascriptcoregtk-4.0-dev libwebkit2gtk-4.0-dev
      - uses: actions/cache@v3
        name: Setup Rust build cache
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: reinismu/clippy-check@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-targets
