on:
  push:
    tags:
      - 'v*'

name: Deploy
jobs:
  draft:
    runs-on: ubuntu-latest
    outputs:
      releaseId: ${{ steps.draft.outputs.test }}
    steps:
      - run: |
          git config --global user.name 'KiwiTalk Continuous Deployment'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'

      - id: draft
        uses: ncipollo/release-action@v1
        with:
          draft: true
          generateReleaseNotes: false
          name: KiwiTalk ${{ github.ref_name }}
          prerelease: true
          tag: ${{ github.ref }}

  build:
    needs: [draft]
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: pnpm/action-setup@v2

      - uses: dtolnay/rust-toolchain@stable

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - uses: Swatinem/rust-cache@v2

      - name: install frontend dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/bundle/**/*.*
          file_glob: true
          tag: ${{ github.ref }}

  publish:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - run: gh release edit ${{ github.ref_name }} --draft=false
