on:
  push:
    tags:
      - 'v*'

env:
  TAG: ${{ github.ref }}

name: Deploy
jobs:
  draft:
    runs-on: ubuntu-latest
    steps:
      - uses: ncipollo/release-action@v1
        with:
          draft: true
          generateReleaseNotes: false
          name: KiwiTalk $TAG
          prerelease: true

  build:
    needs: [draft]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: dtolnay/rust-toolchain@stable
      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
      - uses: Swatinem/rust-cache@v2
      - name: install frontend dependencies
        run: pnpm install
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tauriScript: pnpm build
          releaseId: ${{ needs.draft.outputs.id }}

  publish:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - run: gh release edit $TAG --draft=false
