on:
  workflow_dispatch

name: Deploy
jobs:
  draft:
    runs-on: ubuntu-latest
    outputs:
      releaseId: ${{ steps.draft.outputs.test }}
    steps:
      - uses: actions/checkout@v4

      - run: |
          git config user.name 'KiwiTalk Continuous Deployment'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: pnpm/action-setup@v2

      - uses: dtolnay/rust-toolchain@stable
      
      - uses: Swatinem/rust-cache@v2

      - name: install frontend dependencies
        run: pnpm install

      - name: install cargo-release
        run: cargo install cargo-release

      - id: draft
        run: gh release create ${{ github.ref_name }} --generate-notes -d -t "KiwiTalk ${{ github.ref_name }}"
        env:
          GH_TOKEN: ${{ github.token }}

  build:
    needs: [draft]
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: pnpm/action-setup@v2

      - uses: dtolnay/rust-toolchain@stable

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - uses: Swatinem/rust-cache@v2

      - name: install frontend packages
        run: pnpm install

      - uses: JonasKruckenberg/tauri-build@v1
        id: tauri_build

      - name: upload
        run: gh release upload ${{ github.ref_name }} ${{ join(fromJSON(steps.tauri_build.outputs.artifacts), ' ') }}
        env:
          GH_TOKEN: ${{ github.token }}

  publish:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - run: gh release edit ${{ github.ref_name }} --draft=false
        env:
          GH_TOKEN: ${{ github.token }}
